name: Напоминания о занятиях

on:
  schedule:
        - cron: '4,9,14,19,24,29,34,39,44,49,54,59 * * * *'
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: node reminders.js
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
